import os
import json
import yaml
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional
from secrets_vault import encrypt_secret, decrypt_secret

def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()

ROOT = Path(__file__).resolve().parent
APP_ROOT = ROOT if (ROOT / "config").exists() else ROOT.parent
AGENT_REGISTRY_PATH = APP_ROOT / "agents" / "registry.yaml"
DEPARTMENTS_PATH = APP_ROOT / "config" / "departments.yaml"
MCP_CATALOG_PATH = APP_ROOT / "config" / "mcp_catalog.json"
SETTINGS_PATH = APP_ROOT / "config" / "settings.json"
SECRETS_PATH = APP_ROOT / "config" / "secrets.local.json"
SECRETS_ENV_PATH = APP_ROOT / "config" / "secrets.runtime.env"
MCP_ENV_DIR = APP_ROOT / "config" / "mcp_env"

def json_loads(value: str) -> Dict[str, Any]:
    return json.loads(value)

def json_dumps(value: Dict[str, Any]) -> str:
    return json.dumps(value, indent=2, ensure_ascii=True) + "\n"

def load_mcp_catalog() -> Dict[str, Any]:
    if not MCP_CATALOG_PATH.exists():
        return {"servers": {}}
    return json_loads(MCP_CATALOG_PATH.read_text(encoding="utf-8"))

def save_mcp_catalog(catalog: Dict[str, Any]) -> None:
    MCP_CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    MCP_CATALOG_PATH.write_text(json_dumps(catalog), encoding="utf-8")

def load_settings() -> Dict[str, Any]:
    default_settings = {
        "company_name": "DevFoundry",
        "logo_brand": "",
        "founder": "dfajardo",
        "collaborators": [],
        "theme": "dark",
        "language": "en",
        "tool_policy_mode": os.getenv("TOOL_POLICY_MODE", "approval_required"),
        "voice_conversations_enabled": os.getenv("VOICE_CONVERSATIONS_ENABLED", "false").lower() == "true"
    }
    if not SETTINGS_PATH.exists():
        return default_settings
    try:
        data = json.loads(SETTINGS_PATH.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return {**default_settings, **data}
        return default_settings
    except Exception:
        return default_settings

def save_settings(data: Dict[str, Any]) -> None:
    SETTINGS_PATH.parent.mkdir(parents=True, exist_ok=True)
    SETTINGS_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")

def env_line(key: str, value: str) -> str:
    import re
    if re.fullmatch(r"[A-Za-z0-9_./:@%+=,\-]+", value):
        return f"{key}={value}"
    return f"{key}={json.dumps(value)}"

def write_runtime_env(data: Dict[str, str]) -> None:
    def write_env_file(path: Path, values: Dict[str, str]) -> None:
        lines = [
            "# Generated by the dashboard MCP secrets vault.",
            "# This file is gitignored. Restart docker compose services to apply changes.",
            *[env_line(key, value) for key, value in sorted(values.items())],
        ]
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    SECRETS_ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by the dashboard MCP secrets vault.",
        "# This file is gitignored. Restart docker compose services to apply changes.",
        *[env_line(key, value) for key, value in sorted(data.items())],
    ]
    SECRETS_ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    catalog = load_mcp_catalog()
    for server_name, server in catalog.get("servers", {}).items():
        keys = server.get("env_keys", []) or []
        server_values = {key: data[key] for key in keys if key in data}
        write_env_file(MCP_ENV_DIR / f"{server_name}.env", server_values)

def save_secret_store(data: Dict[str, str]) -> None:
    SECRETS_PATH.parent.mkdir(parents=True, exist_ok=True)
    encrypted_data = {}
    for key, val in data.items():
        if val:
            encrypted_data[key] = encrypt_secret(val)
    SECRETS_PATH.write_text(json_dumps(encrypted_data), encoding="utf-8")
    write_runtime_env(data)
    try:
        SECRETS_PATH.chmod(0o600)
        SECRETS_ENV_PATH.chmod(0o600)
        for path in MCP_ENV_DIR.glob("*.env"):
            path.chmod(0o600)
    except Exception:
        pass

def load_secret_store() -> Dict[str, str]:
    if not SECRETS_PATH.exists():
        return {}
    try:
        data = json_loads(SECRETS_PATH.read_text(encoding="utf-8"))
        result = {}
        needs_migration = False
        for key, value in data.items():
            if not isinstance(key, str):
                continue
            if isinstance(value, str):
                result[key] = value
                if value:
                    needs_migration = True
            else:
                result[key] = decrypt_secret(value)
                
        if needs_migration:
            print("Migrating local secrets store to secure encrypted format...")
            save_secret_store(result)
            
        return result
    except Exception as exc:
        print(f"Error loading secrets from store: {exc}")
        return {}

def declared_secret_keys() -> List[str]:
    keys = {
        "OPENAI_API_KEY", 
        "ANTHROPIC_API_KEY", 
        "GEMINI_API_KEY", 
        "DEEPSEEK_API_KEY", 
        "AZURE_OPENAI_API_KEY", 
        "AZURE_OPENAI_ENDPOINT",
        "AZURE_OPENAI_API_VERSION",
        "XAI_API_KEY",
        "OLLAMA_API_KEY",
        "OLLAMA_BASE_URL",
        "LMSTUDIO_API_KEY",
        "LMSTUDIO_BASE_URL",
        "VLLM_BASE_URL",
        "VLLM_API_KEY"
    }
    for server in load_mcp_catalog().get("servers", {}).values():
        for key in server.get("env_keys", []) or []:
            keys.add(key)
    return sorted(keys)

def mask_secret(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 8:
        return "•" * len(value)
    return f"{value[:3]}{'•' * 8}{value[-4:]}"

def secret_status(key: str, store: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
    store = store if store is not None else load_secret_store()
    local_value = store.get(key)
    env_value = os.getenv(key)
    value = local_value or env_value or ""
    return {
        "key": key,
        "configured": bool(value),
        "masked": mask_secret(value),
        "source": "local_store" if local_value else ("runtime_env" if env_value else "missing"),
    }

def export_mcp_config(client: str, catalog: Dict[str, Any]) -> Dict[str, Any]:
    servers = {
        name: server
        for name, server in catalog.get("servers", {}).items()
        if server.get("enabled") and server.get("kind") == "stdio" and server.get("command")
    }
    if client == "codex":
        blocks = []
        for name, server in servers.items():
            args = ", ".join(f'"{arg}"' for arg in server.get("args", []))
            blocks.append(f'[mcp_servers.{name}]\ncommand = "{server["command"]}"\nargs = [{args}]')
        return {"config_toml": "\n\n".join(blocks)}
    if client == "vscode":
        return {
            "servers": {
                name: {
                    "command": server["command"],
                    "args": server.get("args", []),
                    **({"env": server.get("env")} if server.get("env") else {}),
                }
                for name, server in servers.items()
            }
        }
    return {
        "mcpServers": {
            name: {
                "command": server["command"],
                "args": server.get("args", []),
                **({"env": server.get("env")} if server.get("env") else {}),
            }
            for name, server in servers.items()
        }
    }

def load_agents() -> Dict[str, Any]:
    if not AGENT_REGISTRY_PATH.exists():
        return {"agents": {}}
    return yaml.safe_load(AGENT_REGISTRY_PATH.read_text(encoding="utf-8"))

def save_agents(registry: Dict[str, Any]) -> None:
    AGENT_REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
    AGENT_REGISTRY_PATH.write_text(yaml.safe_dump(registry, sort_keys=False, allow_unicode=False), encoding="utf-8")

def load_departments() -> Dict[str, Any]:
    if not DEPARTMENTS_PATH.exists():
        return {"departments": {}}
    return yaml.safe_load(DEPARTMENTS_PATH.read_text(encoding="utf-8"))

def save_departments(data: Dict[str, Any]) -> None:
    DEPARTMENTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    DEPARTMENTS_PATH.write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=False), encoding="utf-8")
